version: "3"

services:
  aaronkoenescom:
    image: nginx:latest
    container_name: aaronkoenescom
    restart: always
    volumes:
      - ./web-root:/usr/share/nginx/html:ro
      - ./site.conf:/etc/nginx/conf.d/site.conf:ro
    environment:
      - VIRTUAL_HOST=aaronkoenes.com
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true