version: "3"

services:
  aaronkoenescom:
    image: nginx:latest
    container_name: aaronkoenescom
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=resume.local
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true