version: "3"

services:
  image-server:
    image: nginx:latest
    container_name: image-server
    restart: always
    volumes:
      - ./web-root:/usr/share/nginx/html:ro
      - /mnt/Garnet:/media
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site.conf:/etc/nginx/conf.d/site.conf:ro
    environment:
      - VIRTUAL_HOST=images.local
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true